import { Check, RefreshCw, Search, ShieldAlert, X, XCircle } from 'lucide-react';
import { useMemo, useState, type FormEvent } from 'react';
import { apiRequest, formatDate } from '../api/client';
import { PageState } from '../components/PageState';
import { useApiData } from '../hooks/useApiData';
import styles from './DataPage.module.css';

interface ReviewRow { observation: { id: string; valueJson: unknown; evidenceSource: string; moderationStatus: string; evidenceGrade: string; freshnessStatus: string; confidence: string | null; createdAt: string; expiresAt: string | null }; placeName: string }

export function ReviewsPage() {
  const rows = useApiData<ReviewRow[]>('/api/v1/admin/reviews'); const [query, setQuery] = useState(''); const [selected, setSelected] = useState<ReviewRow | null>(null);
  const filtered = useMemo(() => (rows.data ?? []).filter((row) => row.placeName.toLowerCase().includes(query.toLowerCase())), [rows.data, query]);
  return <div className={styles.page}><header className={styles.heading}><div><p>证据治理</p><h1>证据审核</h1><span>管理员只能审核来源与内容；A 级认证必须继续遵守官方材料和双人审批规则。</span></div><button className={styles.secondaryButton} onClick={() => void rows.reload()}><RefreshCw size={17} />刷新</button></header><div className={styles.toolbar}><label className={styles.search}><Search size={18} /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索地点" /></label><span className={styles.muted}>共 {filtered.length} 条</span></div><section className={styles.card}><PageState loading={rows.loading} error={rows.error} empty={!rows.loading && filtered.length === 0} onRetry={rows.reload} />{filtered.length > 0 && <div className={styles.tableWrap}><table className={styles.table}><thead><tr><th>地点</th><th>来源</th><th>当前状态</th><th>等级</th><th>新鲜度</th><th>提交时间</th><th>操作</th></tr></thead><tbody>{filtered.map((row) => <tr key={row.observation.id}><td><strong>{row.placeName}</strong><br/><code>{row.observation.id}</code></td><td>{row.observation.evidenceSource}</td><td><span className={`${styles.chip} ${row.observation.moderationStatus === 'pending' ? styles.pending : row.observation.moderationStatus === 'accepted' ? styles.success : styles.danger}`}>{row.observation.moderationStatus}</span></td><td>{row.observation.evidenceGrade}</td><td>{row.observation.freshnessStatus}</td><td>{formatDate(row.observation.createdAt)}</td><td><button className={styles.rowButton} onClick={() => setSelected(row)}>审核</button></td></tr>)}</tbody></table></div>}</section>{selected && <ReviewDrawer row={selected} onClose={() => setSelected(null)} onSaved={() => { setSelected(null); void rows.reload(); }} />}</div>;
}

function ReviewDrawer({ row, onClose, onSaved }: { row: ReviewRow; onClose: () => void; onSaved: () => void }) {
  const [decision, setDecision] = useState<'accepted' | 'rejected' | 'pending'>('accepted'); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSaving(true); setError(null); const reason = new FormData(event.currentTarget).get('reason'); try { await apiRequest(`/api/v1/admin/reviews/${row.observation.id}/decision`, { method: 'POST', body: JSON.stringify({ decision, reason }) }); onSaved(); } catch (reasonValue) { setError(reasonValue instanceof Error ? reasonValue.message : '审核失败'); } finally { setSaving(false); } };
  return <div className={styles.drawer} onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><aside className={styles.drawerPanel} role="dialog" aria-modal="true"><div className={styles.drawerHeader}><div><ShieldAlert /><h2>审核证据</h2><p className={styles.muted}>{row.placeName}</p></div><button className={styles.iconButton} onClick={onClose} aria-label="关闭"><X /></button></div><dl className={styles.detailList}><div><dt>证据 ID</dt><dd>{row.observation.id}</dd></div><div><dt>来源</dt><dd>{row.observation.evidenceSource}</dd></div><div><dt>当前等级</dt><dd>{row.observation.evidenceGrade}</dd></div><div><dt>置信度</dt><dd>{row.observation.confidence ?? '未提供'}</dd></div></dl><pre className={styles.json}>{JSON.stringify(row.observation.valueJson, null, 2)}</pre><form className={styles.form} onSubmit={submit}><label>审核结论<select value={decision} onChange={(event) => setDecision(event.target.value as typeof decision)}><option value="accepted">接受为 C 级社区观测</option><option value="rejected">驳回</option><option value="pending">退回待处理</option></select></label><label>审核理由<textarea name="reason" required minLength={3} maxLength={1000} placeholder="说明证据是否清晰、是否匹配地点与字段" /></label>{error && <div className={styles.error}>{error}</div>}<div className={styles.formActions}><button type="button" className={styles.secondaryButton} onClick={onClose}>取消</button><button className={decision === 'rejected' ? styles.dangerButton : styles.primaryButton} disabled={saving}>{decision === 'rejected' ? <><XCircle size={17}/>确认驳回</> : <><Check size={17}/>保存结论</>}</button></div></form></aside></div>;
}
